### ISSUE TITLE
Lack of "nms_cuda.c" when compile the "make.sh"

### ISSUE THREAD

**Issue by wangken1994** [tztztztztz/faster_rcnn.pytorch#1]
Hi, @tztztztztz 
An error occurred in my terminal when I ran `sh make.sh`, the errors were shown below:
```
gcc: error: .../faster-rcnn.pytorch-master/faster_rcnn/nms/src/nms_cuda.c: 没有那个文件或目录
gcc: fatal error: no input files
```
I think this is due to the lack of the `nms_cuda.c` file in `/nms/src`. So could you give me some help?
Best!

**Comment by tztztztztz** [comment]
Sorry, I've added it.

**Comment by wangken1994** [comment]
Thank you so much! @tztztztztz 
I can run the source codes now.
